<?php

declare(strict_types=1);

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * A model describing its columns with PHPDoc (as generated by IDE helper tools).
 *
 * @property int    $id
 * @property string $email
 * @property string $display_name
 */
class UserWithPropertyTags extends Model
{
    protected $table = 'users';
}
